### ISSUE TITLE
关于tracking retrieval部分的实现

### ISSUE THREAD

**Issue by hszh** [1vpmaster/SimpleTrack#3]
您在tracking retrieval部分提到，在卡尔曼滤波预测中心点附近3×3范围内提取候选的表观特征向量，但我在代码中并没有找到体现3×3范围的地方，您方便的话能指点一下吗？

**Comment by 1vpmaster** [comment]
您好，在EG_tracker.py文件中的382-401行可以看到这部分找回工作的实现，在这个版本中，我们直接利用了卡尔曼滤波预测得到的位置的reid特征进行阈值约束（ps: 与3x3效果接近，但速度更快）。
如果想使用r*r范围的话，可以直接在这部分代码中进行修改。
lines 385:  track_index = self.reback_post_process(track, meta_reback, meta) # 对应卡尔曼滤波预测的中心点位置
依据此位置可以计算得到r*r范围的所有位置坐标，再提取每个坐标点的特征向量，最后求出最相似的位置即可。

**Comment by hszh** [comment]
明白了，感谢您的及时回复。

**Comment by YanhuiS** [comment]
作者你好，请问你这说的“卡尔曼滤波预测得到的位置的reid特征进行阈值约束”是说 卡尔曼滤波预测的中心点位置对应的128维特征与 剩余没有匹配轨迹的smooth_feature的cosine距离  小于某个约束时就更新的意思吗？
