### ISSUE TITLE
为什么投Sensors

### ISSUE THREAD

**Issue by Bian-666** [1vpmaster/SimpleTrack#4]

**Comment by 1vpmaster** [comment]
之前投ECCV没中，然后要赶毕业要求，投这个了，哭。。。

**Comment by Bian-666** [comment]
> 之前投ECCV没中，然后要赶毕业要求，投这个了，哭。。。

原来如此，可这个不是预警期刊吗

**Comment by 1vpmaster** [comment]
现在已经不是预警期刊了，况且我不是博士

**Comment by Bian-666** [comment]
> 现在已经不是预警期刊了，况且我不是博士

请问MOTchanllenge的账号是怎么注册上的？

**Comment by 1vpmaster** [comment]
就按照官网一步一步来就好了呀

**Comment by Bian-666** [comment]
> 

你这么顺利的吗，用的是学校邮箱吗？

**Comment by Bian-666** [comment]
> 就按照官网一步一步来就好了呀

你这么顺利的吗，用的是学校邮箱吗？

**Comment by 1vpmaster** [comment]
是的

**Comment by Bian-666** [comment]
> 是的

请问有什么方法吗，我注册之后一直没有回复
