### ISSUE TITLE
paper中的networks

### ISSUE THREAD

**Issue by faicavt0937240** [1vpmaster/SimpleTrack#5]
/src/lib/models/networks下有很多networks。
想問一下paper中的網路以及實作是使用dlav0.py這個檔案嗎?

另外dla_cs.py、multi_dla_decouple.py和原本的差別是?當中加入了paper沒有提及的部分(注意力等等......)

**Comment by 1vpmaster** [comment]
感谢您的提问，代码中使用得主干网络可以从训练和测试的代码中找到，具体可以看opt.py中的网络设置。另外关于dla_cs.py和multi_dla_decouple.py是实验中的废弃版本，前者是dla网络加入cstrack的解耦结构，后者是多帧图像输入的解耦主干网络设计。

**Comment by faicavt0937240** [comment]
感謝您的回覆。
根據train 以及 opt default設定。create model應該會使用 pose_dla_decouple.py去建置model，前面的pose命名是否具有意義，以及當中有def attention 是否是後續增加的，paper當中好像沒有提及到這樣的部分，大概會想這麼增加的主因是?。

model.py 的_model_factory dlav0後面指的# default DLAup 單純只是指原本的DLAup參考用，對於您的實驗來說並沒有使用到嗎。

另外dla_cs.py和multi_dla_decouple.py實驗中的2個廢棄版本廢棄的原因是?因為我也想要在dla當中使用一些解偶結構，解偶的這幾篇都有去看過，正想要嘗試看看。

謝謝

**Comment by faicavt0937240** [comment]
> 后者是多帧图像输入的解耦主干网络设计

另外想要問multi_dla_decouple.py這個網路，有不少paper也會加入多楨輸入，去改善得到更好的結果或者獲得一些幫助，例如幫助偵測或是預測offset的結果。

multi_dla_decouple.py 是paper實驗中使用的pose_dla_decouple.py這個的多楨輸入版本嗎?放棄的原因是結果更差?、取捨?又或者是什麼原因呢?

謝謝

**Comment by 1vpmaster** [comment]
在进行实验中，本来是想利用MEGA的方法提升目标被遮挡时的特征鲁棒性，但是我尝试训练了一个月左右的多帧融合方法，发现跟踪效果难以进一步提升。

**Comment by 1vpmaster** [comment]
关于dla_cs的实验，我发现在dla后加入cstrack的方法，训练结果很不稳定

**Comment by faicavt0937240** [comment]
> 关于dla_cs的实验，我发现在dla后加入cstrack的方法，训练结果很不稳定

了解了，非常感謝。

**Comment by 1vpmaster** [comment]
好的，那我把issue关了
