### ISSUE TITLE
Tracking Strategy

### ISSUE THREAD

**Issue by YanhuiS** [1vpmaster/SimpleTrack#7]
作者你好，感谢你的greet work！我想请问一下你在image.py代码中transform_preds函数的用途是什么？，get_affine_transform函数中寻找变化变化矩阵为什么使用dst和src这三个点，别的三个点可以吗？你是出于什么考虑？

**Comment by 1vpmaster** [comment]
这个image.py代码是fairmot这篇工作写的，我没太注意图像预处理这部分的工作

**Comment by YanhuiS** [comment]
好的，谢谢。https://github.com/1vpmaster/SimpleTrack/issues/3#issuecomment-1231231875，请问你这说的“卡尔曼滤波预测得到的位置的reid特征进行阈值约束”是说 卡尔曼滤波预测的中心点位置对应的128维特征与 剩余没有匹配轨迹的smooth_feature的cosine距离 小于某个约束时就更新的意思吗？

**Comment by 1vpmaster** [comment]
是的，也可以选卡尔曼滤波中心点位置周围几个点的特征向量进行综合评估，毕竟卡尔曼滤波预测的位置不是精确值

**Comment by YanhuiS** [comment]
好的，谢谢
