### ISSUE TITLE
What is the machine spec required to run SimpleTrack?

### ISSUE THREAD

**Issue by Mittag-tech** [1vpmaster/SimpleTrack#8]
Hi @1vpmaster ,

I would try to make environment to use SimpleTrack.
But, I don't know whether my machine have a enough spec to train or track.
Can you tell me what machine specs you run SimpleTrack on, especially the memory size and number of GPU?

**Comment by 1vpmaster** [comment]
Thank you for your attention to our work, our work based on the fairmot algorithm，you can find detailed information in this repo. But, I can give you some suggestions, we trained our work on 4 x RTXTitan(4 x 24G) machine. And, we inference on the single RTX2080Ti, the GPU memory takes up about 4G.

**Comment by Mittag-tech** [comment]
Thank you for your response, @1vpmaster .

> our work based on the fairmot algorithm，

> we trained our work on 4 x RTXTitan(4 x 24G) machine. And, we inference on the single RTX2080Ti, the GPU memory takes up about 4G.

It is good information for me.
Thanks !
